baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Portefeuille de Comp√©tences Professionnel'
theme = ["github.com/D-Sketon/hugo-theme-reimu"]
relativeURLs = false
canonifyURLs = true
[markup]
    [markup.goldmark.renderer]
        unsafe = true